### ISSUE TITLE
Ability to get map entries from API

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain-sidecar#141]
I’ve been thinking about a bunch hypothetical clarity-using apps. One “feature” that always seems to pop up as a requirement is the ability to programmatically get entries from a contract’s map. Not in Clarity itself - from the sidecar API. I’m poking around the sidecar, and I’m not quite sure if this is possible right now.

Here is the hypothetical API I'd want:

`GET /api/sidecar/v1/contracts/:contract/map-entries/:map-var-name`

This would be a paginate-able API, and would return an array of key/value pairs.

Questions:

- If this is possible, how can I learn more about the underlying DB tables, so that I could potentially implement it?
- If this isn't possible at the moment, what is required to enable such functionality?

I'm hoping to learn more about the sidecar's datastore through this, and less-so asking for this to be implemented without question.

I know that I could hack around this by keeping an in-Clarity map like `my-map-entries`, where the key is `(index uint)` and the value is the key for that map entry. Then, I could use the RPC API to get each map key by index, and then query for the value of that map key. However, that's hugely inefficient and goes straight to the core node, both of which are not ideal.

**Comment by psq** [comment]
@hstove I have been wondering along the same line as having the ability to get the whole map would certainly be useful for a few app ideas I've considered.

So I'd love to see this functionality added one way or an other!

There is a better (or so I think) way in Clarity to implement what you are suggesting without relying on a `uint` key and making lots of calls: by combining a `map` and a `list`.  See [adding](https://github.com/psq/swapr/blob/master/contracts/swapr-registry.clar#L76-L77) and [getting the whole map](https://github.com/psq/swapr/blob/master/contracts/swapr-registry.clar#L99-L101).  Although you are subject to size limits on the `list`, but in my case, that was going to be presumably fine.  Pagination might be doable, by my head hurts just trying to think on how best to do it in Clarity...

That said, the map data residing in the database of the node itself, it would make more sense to first add the whole map retrieval on the RPC API of the node, which already provides the ability to retrieve one map value (`/v2/map_entry/[contract_address]/[contract_name]/[map_name]`, passing the hex of the serialized key in the body, [implementation](https://github.com/blockstack/stacks-blockchain/blob/master/src/net/rpc.rs#L485)).  Not sure it would make sense to duplicate the data in sidecar, but it would just proxy it as it is done for all RPC node endpoints exposed by sidecar.
