### ISSUE TITLE
Use of ISO 8601, rather than epoch

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-sidecar#157]
I'm using the `burn_block_time` property in the [Stacks Wallet](https://github.com/blockstack/stacks-wallet/), which is coded as a second-based epoch value.

There's the inconsistency with unix time that it can be either second or millisecond based. It's also not very human readable.

Any objections to using the ISO 8601 standard for date/time values, rather than timestamps?

**Comment by zone117x** [comment]
The burn block time is the actual value included in the bitcoin block, I think it's valuable to include that data. But yeah not very readable, we could add an additional property like `burn_block_time_string` or something?

**Comment by kyranjamie** [comment]
Both works for me. `burn_block_time_iso`?
