### ISSUE TITLE
Json schema/types for API block data

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-sidecar#9]
Likely the JSON representation of the postgres query result, e.g. 
`select * from transactions where tx = $1`
`select * from blocks where hash = $1`

Needed for various consumers projects, for example a chainwalker parser https://docs.flipsidecrypto.com/chainwalkers-framework/chainwalkers-getting-started/chainwalkers-writing-the-parser

**Comment by zone117x** [comment]
The tx json schema is completed in this PR https://github.com/blockstack/stacks-blockchain-sidecar/pull/27

Block json schema still pending.

**Comment by agraebe** [comment]
@kyranjamie could you help with this ticket?

**Comment by kyranjamie** [comment]
I'm not entirely sure what the ask is here, @agraebe?

**Comment by diwakergupta** [comment]
> Likely the JSON representation of the postgres query result, e.g.
> `select * from transactions where tx = $1`
> `select * from blocks where hash = $1`
> 
> Needed for various consumers projects, for example a chainwalker parser https://docs.flipsidecrypto.com/chainwalkers-framework/chainwalkers-getting-started/chainwalkers-writing-the-parser

Note that we are already live with flipside on Stacks 1.0, so there's no immediate blocker here. We'll want to make sure they can port over the chainwalker to Stacks 2.0 upon mainnet launch, so at some point before then we might need this but just wanted to clarify that the chainwalker use-case isn't an immediate priority. I'm also not sure if chainwalkers will need to (or even should) use the sidecar API vs. the core API directly, FWIW.

**Comment by aulneau** [comment]
@kyranjamie my understanding is that the ask is to define the types for the block api response to be found within the sidecar types library, as was done for /tx, etc. This is related to implementing block data within the explorer.

**Comment by zone117x** [comment]
Yep ^
Schema / types for the block response. No worries if you don't have bandwidth

**Comment by kyranjamie** [comment]
I've made a quick PR here with the set up/initial structure for how a block should look https://github.com/blockstack/stacks-blockchain-sidecar/pull/122

To flesh it out more thoroughly, would need to jump into the designs/implementation. Would be great if you guys can pick this up when you're building it, and have a clearer idea what its missing.
